[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
clap_complete = "4.5.58"
clap_mangen = "0.2.29"
devenv.workspace = true
miette.workspace = true
