name: "Build"

on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref to checkout"
        required: false
        type: string
      system:
        description: "System to build for"
        required: true
        type: string
      runs-on:
        description: "Runner to use"
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    outputs:
      devenv-path: ${{ steps.build-devenv.outputs.path }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Configure Cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build devenv-${{ inputs.system }}
        id: build-devenv
        run: |
          devenv_path=$(nix build -L --show-trace --print-out-paths --system ${{ inputs.system }} .#devenv)
          echo "path=$devenv_path" >> $GITHUB_OUTPUT

      # Build and cache the devenv-tasks binary used by the module system
      - name: Build devenv-tasks-fast-build-${{ inputs.system }}
        run: |
          nix build -L --show-trace --print-out-paths --system ${{ inputs.system }} .#devenv-tasks-fast-build

      - name: Run integration tests
        run: |
          ${{ steps.build-devenv.outputs.path }}/bin/devenv shell -- cargo test --all-features
